# Partimos de la imagen php en su versión 7.4
FROM php:8.2-cli

# Copiamos los archivos package.json composer.json y composer-lock.json a /var/www/
COPY composer*.json /var/www/

# Nos movemos a /var/www/
WORKDIR /var/www/

# Instalamos las dependencias necesarias
RUN apt-get update && apt-get install -y \
    build-essential \
    libzip-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    git \
    curl

# Instalamos extensiones de PHP
RUN docker-php-ext-install pdo_mysql zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd

# Instalamos composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Actualizamos composer
RUN composer self-update

# Eliminamos cualquier contenido existente en el directorio de trabajo
RUN rm -rf /var/www/*

# Creamos el proyecto de Laravel sin las dependencias de desarrollo (--no-dev)
RUN composer create-project --prefer-dist --no-dev laravel/laravel .

# Instalamos las dependencias de producción únicamente
RUN composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts

# Exponemos el puerto 81
EXPOSE 81

# Inicia el servidor web de PHP en el puerto 81
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=81"]